const ARTISANS = [
  {id:1,name:"Sunita Das",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:44},
  {id:2,name:"Amit Iyer",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:27},
  {id:3,name:"Amit Mishra",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:19},
  {id:4,name:"Amit Joshi",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:11},
  {id:5,name:"Rohan Bose",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:45},
  {id:6,name:"Amit Sharma",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:23},
  {id:7,name:"Vijay Kulkarni",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:9},
  {id:8,name:"Arjun Patel",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:33},
  {id:9,name:"Geeta Bahl",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:15},
  {id:10,name:"Vijay Das",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:25},
  {id:11,name:"Vikram Reddy",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:4},
  {id:12,name:"Suresh Iyer",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:25},
  {id:13,name:"Lakshmi Das",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:24},
  {id:14,name:"Sunita Mehta",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:17},
  {id:15,name:"Manoj Iyer",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:13},
  {id:16,name:"Kartik Tiwari",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:19},
  {id:17,name:"Rohan Mehta",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:4},
  {id:18,name:"Kavita Joshi",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:28},
  {id:19,name:"Anjali Sahay",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:13},
  {id:20,name:"Sunita Das",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:44},
  {id:21,name:"Lakshmi Nair",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:16},
  {id:22,name:"Manoj Das",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:14},
  {id:23,name:"Manoj Yadav",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:27},
  {id:24,name:"Sita Mehta",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:11},
  {id:25,name:"Kavita Mishra",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:13},
  {id:26,name:"Manoj Singh",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:34},
  {id:27,name:"Raj Yadav",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:10},
  {id:28,name:"Rahul Kulkarni",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:43},
  {id:29,name:"Sita Bose",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:5},
  {id:30,name:"Arjun Bahl",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:39},
  {id:31,name:"Suresh Yadav",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:19},
  {id:32,name:"Meena Tiwari",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:35},
  {id:33,name:"Kavita Nair",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:3},
  {id:34,name:"Meena Tiwari",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:39},
  {id:35,name:"Amit Chatterjee",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:13},
  {id:36,name:"Amit Bahl",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:5},
  {id:37,name:"Rohan Kulkarni",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:16},
  {id:38,name:"Anjali Khan",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:38},
  {id:39,name:"Pooja Khan",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:4},
  {id:40,name:"Vikram Sahay",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:11},
  {id:41,name:"Amit Sharma",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:20},
  {id:42,name:"Amit Mehta",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:4},
  {id:43,name:"Meena Chatterjee",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:20},
  {id:44,name:"Kavita Verma",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:8},
  {id:45,name:"Suresh Singh",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:12},
  {id:46,name:"Manoj Nair",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:12},
  {id:47,name:"Manoj Sahay",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:27},
  {id:48,name:"Meena Joshi",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:8},
  {id:49,name:"Rekha Reddy",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:8},
  {id:50,name:"Suresh Bose",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:7},
  {id:51,name:"Anjali Tiwari",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:34},
  {id:52,name:"Arjun Das",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:14},
  {id:53,name:"Geeta Chatterjee",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:17},
  {id:54,name:"Deepa Tiwari",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:42},
  {id:55,name:"Rahul Patel",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:11},
  {id:56,name:"Amit Mehta",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:25},
  {id:57,name:"Manoj Singh",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:45},
  {id:58,name:"Pooja Gupta",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:43},
  {id:59,name:"Kavita Chatterjee",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:15},
  {id:60,name:"Deepa Das",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:20},
  {id:61,name:"Geeta Kulkarni",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:29},
  {id:62,name:"Anjali Sahay",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:21},
  {id:63,name:"Vikram Yadav",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:23},
  {id:64,name:"Pooja Sahay",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:29},
  {id:65,name:"Sita Kulkarni",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:11},
  {id:66,name:"Anjali Yadav",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:31},
  {id:67,name:"Meena Iyer",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:35},
  {id:68,name:"Vikram Patel",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:42},
  {id:69,name:"Sunita Singh",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:40},
  {id:70,name:"Rohan Sharma",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:25},
  {id:71,name:"Vikram Reddy",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:9},
  {id:72,name:"Raj Khan",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:40},
  {id:73,name:"Rekha Mishra",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:31},
  {id:74,name:"Pooja Mishra",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:32},
  {id:75,name:"Rahul Kulkarni",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:33},
  {id:76,name:"Anjali Mishra",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:17},
  {id:77,name:"Rahul Reddy",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:36},
  {id:78,name:"Sita Bahl",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:5},
  {id:79,name:"Vikram Joshi",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:3},
  {id:80,name:"Geeta Sharma",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:31},
  {id:81,name:"Kartik Iyer",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:13},
  {id:82,name:"Deepa Das",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:45},
  {id:83,name:"Raj Reddy",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:34},
  {id:84,name:"Geeta Singh",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:10},
  {id:85,name:"Raj Bahl",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:26},
  {id:86,name:"Manoj Sharma",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:34},
  {id:87,name:"Vijay Reddy",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:39},
  {id:88,name:"Rahul Bahl",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:16},
  {id:89,name:"Sunita Bose",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:6},
  {id:90,name:"Manoj Singh",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:30},
  {id:91,name:"Rohan Bose",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:19},
  {id:92,name:"Kavita Sharma",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:5},
  {id:93,name:"Rahul Joshi",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:23},
  {id:94,name:"Rekha Mehta",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:29},
  {id:95,name:"Kartik Das",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:45},
  {id:96,name:"Amit Patel",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:36},
  {id:97,name:"Amit Chatterjee",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:16},
  {id:98,name:"Geeta Iyer",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:8},
  {id:99,name:"Rohan Khan",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:10},
  {id:100,name:"Kartik Chatterjee",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:19},
  {id:101,name:"Sita Sharma",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:42},
  {id:102,name:"Rekha Joshi",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:12},
  {id:103,name:"Raj Joshi",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:7},
  {id:104,name:"Kavita Khan",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:13},
  {id:105,name:"Pooja Das",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:3},
  {id:106,name:"Raj Bahl",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:27},
  {id:107,name:"Raj Chatterjee",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:44},
  {id:108,name:"Arjun Verma",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:26},
  {id:109,name:"Raj Kulkarni",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:29},
  {id:110,name:"Sita Reddy",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:30},
  {id:111,name:"Deepa Sharma",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:3},
  {id:112,name:"Raj Mehta",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:4},
  {id:113,name:"Vikram Bose",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:4},
  {id:114,name:"Rekha Iyer",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:22},
  {id:115,name:"Sunita Singh",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:35},
  {id:116,name:"Kavita Patel",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:12},
  {id:117,name:"Meena Sahay",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:7},
  {id:118,name:"Sunita Joshi",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:10},
  {id:119,name:"Kartik Singh",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:43},
  {id:120,name:"Rekha Chatterjee",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:37},
  {id:121,name:"Vijay Mehta",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:33},
  {id:122,name:"Vikram Bose",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:34},
  {id:123,name:"Suresh Nair",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:5},
  {id:124,name:"Deepa Sharma",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:36},
  {id:125,name:"Geeta Singh",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:28},
  {id:126,name:"Lakshmi Reddy",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:12},
  {id:127,name:"Sita Tiwari",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:13},
  {id:128,name:"Vijay Sharma",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:45},
  {id:129,name:"Vijay Mishra",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:12},
  {id:130,name:"Arjun Yadav",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:11},
  {id:131,name:"Suresh Sharma",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:3},
  {id:132,name:"Arjun Yadav",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:22},
  {id:133,name:"Vikram Mehta",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:25},
  {id:134,name:"Geeta Sahay",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:4},
  {id:135,name:"Lakshmi Sharma",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:7},
  {id:136,name:"Geeta Joshi",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:38},
  {id:137,name:"Geeta Bahl",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:3},
  {id:138,name:"Meena Bahl",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:31},
  {id:139,name:"Kartik Iyer",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:27},
  {id:140,name:"Lakshmi Yadav",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:16},
  {id:141,name:"Rahul Mehta",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:43},
  {id:142,name:"Lakshmi Bose",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:37},
  {id:143,name:"Anjali Verma",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:12},
  {id:144,name:"Manoj Tiwari",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:41},
  {id:145,name:"Vikram Kulkarni",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:33},
  {id:146,name:"Anjali Reddy",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:30},
  {id:147,name:"Anjali Nair",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:22},
  {id:148,name:"Vijay Patel",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:17},
  {id:149,name:"Rahul Tiwari",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:28},
  {id:150,name:"Sita Bahl",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:9},
  {id:151,name:"Arjun Bose",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:22},
  {id:152,name:"Rohan Iyer",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:31},
  {id:153,name:"Suresh Kulkarni",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:25},
  {id:154,name:"Suresh Kulkarni",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:23},
  {id:155,name:"Rohan Patel",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:32},
  {id:156,name:"Sunita Mishra",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:39},
  {id:157,name:"Rahul Tiwari",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:38},
  {id:158,name:"Anjali Kulkarni",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:38},
  {id:159,name:"Suresh Tiwari",craft:"Hand Block Printing",location:"Jaipur, Rajasthan",city:"Jaipur",exp:37},
  {id:160,name:"Manoj Patel",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:27},
  {id:161,name:"Vijay Sharma",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:29},
  {id:162,name:"Sita Sahay",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:23},
  {id:163,name:"Deepa Singh",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:6},
  {id:164,name:"Anjali Reddy",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:9},
  {id:165,name:"Lakshmi Khan",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:31},
  {id:166,name:"Vikram Gupta",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:26},
  {id:167,name:"Anjali Bose",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:12},
  {id:168,name:"Rohan Das",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:24},
  {id:169,name:"Anjali Sahay",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:4},
  {id:170,name:"Kartik Iyer",craft:"Bagh Print",location:"Dhar, Madhya Pradesh",city:"Dhar",exp:25},
  {id:171,name:"Rekha Singh",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:30},
  {id:172,name:"Anjali Iyer",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:43},
  {id:173,name:"Manoj Singh",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:28},
  {id:174,name:"Raj Chatterjee",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:38},
  {id:175,name:"Rekha Sharma",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:38},
  {id:176,name:"Meena Iyer",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:28},
  {id:177,name:"Anjali Sahay",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:29},
  {id:178,name:"Manoj Singh",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:24},
  {id:179,name:"Meena Patel",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:9},
  {id:180,name:"Deepa Sharma",craft:"Ajrakh Printing",location:"Kutch, Gujarat",city:"Kutch",exp:13},
  {id:181,name:"Rahul Yadav",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:35},
  {id:182,name:"Deepa Gupta",craft:"Kanchipuram Silk Weaving",location:"Kanchipuram, Tamil Nadu",city:"Kanchipuram",exp:16},
  {id:183,name:"Rahul Singh",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:9},
  {id:184,name:"Geeta Bahl",craft:"Pashmina Weaving",location:"Srinagar, Jammu & Kashmir",city:"Srinagar",exp:19},
  {id:185,name:"Lakshmi Tiwari",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:18},
  {id:186,name:"Amit Bose",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:3},
  {id:187,name:"Rahul Verma",craft:"Toda Embroidery",location:"Nilgiris, Tamil Nadu",city:"Nilgiris",exp:3},
  {id:188,name:"Geeta Chatterjee",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:23},
  {id:189,name:"Arjun Khan",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:4},
  {id:190,name:"Rohan Tiwari",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:36},
  {id:191,name:"Rohan Verma",craft:"Kantha Stitch",location:"Shantiniketan, West Bengal",city:"Shantiniketan",exp:40},
  {id:192,name:"Kartik Tiwari",craft:"Leather Jutti Making",location:"Jodhpur, Rajasthan",city:"Jodhpur",exp:29},
  {id:193,name:"Rohan Reddy",craft:"Pattachitra Painting",location:"Raghurajpur, Odisha",city:"Raghurajpur",exp:8},
  {id:194,name:"Rohan Verma",craft:"Chikan Embroidery",location:"Lucknow, Uttar Pradesh",city:"Lucknow",exp:29},
  {id:195,name:"Kartik Mehta",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:18},
  {id:196,name:"Kartik Bahl",craft:"Phulkari Embroidery",location:"Patiala, Punjab",city:"Patiala",exp:44},
  {id:197,name:"Lakshmi Singh",craft:"Dhokra Metal Casting",location:"Bastar, Chhattisgarh",city:"Bastar",exp:30},
  {id:198,name:"Rahul Verma",craft:"Bamboo Craft",location:"Agartala, Tripura",city:"Agartala",exp:16},
  {id:199,name:"Geeta Sahay",craft:"Blue Pottery",location:"Jaipur, Rajasthan",city:"Jaipur",exp:23},
  {id:200,name:"Kavita Gupta",craft:"Bidriware",location:"Bidar, Karnataka",city:"Bidar",exp:3},
];

const MATERIALS = [
  {name:"Cotton Fabric",craft:"Hand Block Printing",region:"Jaipur"},
  {name:"Natural Dyes (Indigo/Madder)",craft:"Hand Block Printing",region:"Jaipur"},
  {name:"Teak Wood Blocks",craft:"Hand Block Printing",region:"Jaipur"},
  {name:"Alum",craft:"Hand Block Printing",region:"Jaipur"},
  {name:"Grey Cloth",craft:"Ajrakh Printing",region:"Kutch"},
  {name:"Myrobalan",craft:"Ajrakh Printing",region:"Kutch"},
  {name:"Camel Dung",craft:"Ajrakh Printing",region:"Kutch"},
  {name:"Iron Scrap",craft:"Ajrakh Printing",region:"Kutch"},
  {name:"Jaggery",craft:"Ajrakh Printing",region:"Kutch"},
  {name:"Mulmul/Muslin",craft:"Chikan Embroidery",region:"Lucknow"},
  {name:"Needle",craft:"Chikan Embroidery",region:"Lucknow"},
  {name:"Embroidery Hoop",craft:"Chikan Embroidery",region:"Lucknow"},
  {name:"Cotton Thread",craft:"Chikan Embroidery",region:"Lucknow"},
  {name:"Tussar Silk",craft:"Pattachitra Painting",region:"Raghurajpur"},
  {name:"Stone Pigments",craft:"Pattachitra Painting",region:"Raghurajpur"},
  {name:"Conch Shell Powder",craft:"Pattachitra Painting",region:"Raghurajpur"},
  {name:"Wood Apple Resin",craft:"Pattachitra Painting",region:"Raghurajpur"},
  {name:"Mulberry Silk",craft:"Kanchipuram Silk Weaving",region:"Kanchipuram"},
  {name:"Silver Zari",craft:"Kanchipuram Silk Weaving",region:"Kanchipuram"},
  {name:"Gold Thread",craft:"Kanchipuram Silk Weaving",region:"Kanchipuram"},
  {name:"Rice Starch",craft:"Kanchipuram Silk Weaving",region:"Kanchipuram"},
  {name:"Changthangi Goat Wool",craft:"Pashmina Weaving",region:"Srinagar"},
  {name:"Natural Dyes",craft:"Pashmina Weaving",region:"Srinagar"},
  {name:"Hand-operated Loom",craft:"Pashmina Weaving",region:"Srinagar"},
  {name:"Quartz Stone Powder",craft:"Blue Pottery",region:"Jaipur"},
  {name:"Glass",craft:"Blue Pottery",region:"Jaipur"},
  {name:"Multani Mitti",craft:"Blue Pottery",region:"Jaipur"},
  {name:"Cobalt Oxide",craft:"Blue Pottery",region:"Jaipur"},
  {name:"Brass Scrap",craft:"Dhokra Metal Casting",region:"Bastar"},
  {name:"Beeswax",craft:"Dhokra Metal Casting",region:"Bastar"},
  {name:"Clay",craft:"Dhokra Metal Casting",region:"Bastar"},
  {name:"Coal",craft:"Dhokra Metal Casting",region:"Bastar"},
  {name:"Old Sarees/Cotton",craft:"Kantha Stitch",region:"Shantiniketan"},
  {name:"Needles",craft:"Kantha Stitch",region:"Shantiniketan"},
  {name:"Colored Embroidery Thread",craft:"Kantha Stitch",region:"Shantiniketan"},
  {name:"Hand-woven Cotton",craft:"Toda Embroidery",region:"Nilgiris"},
  {name:"Woolen Threads (Red/Black)",craft:"Toda Embroidery",region:"Nilgiris"},
  {name:"Zinc",craft:"Bidriware",region:"Bidar"},
  {name:"Copper",craft:"Bidriware",region:"Bidar"},
  {name:"Ammonium Chloride",craft:"Bidriware",region:"Bidar"},
  {name:"Soil from Bidar Fort",craft:"Bidriware",region:"Bidar"},
  {name:"Khaddar Fabric",craft:"Phulkari Embroidery",region:"Patiala"},
  {name:"Pat (Untwisted Silk Thread)",craft:"Phulkari Embroidery",region:"Patiala"},
  {name:"Red/Black Dyes",craft:"Bagh Print",region:"Dhar"},
  {name:"Wooden Blocks",craft:"Bagh Print",region:"Dhar"},
  {name:"Muli Bamboo",craft:"Bamboo Craft",region:"Agartala"},
  {name:"Knives/Chisels",craft:"Bamboo Craft",region:"Agartala"},
  {name:"Varnish",craft:"Bamboo Craft",region:"Agartala"},
  {name:"Camel Leather",craft:"Leather Jutti Making",region:"Jodhpur"},
  {name:"Embroidery Zari",craft:"Leather Jutti Making",region:"Jodhpur"},
];
